### PR TITLE
Add station names to channelInfoList

### PR DESCRIPTION
**Pull request by jspricke**
Taken from:

https://github.com/mediathekview/zapp/blob/master/app/src/main/res/raw/channels.json

### CODE REVIEW

**Comment by cemrich** [comment]
Thank you very much for this pull request. This looks reasonable and I'll look into it as soon as I have some spare time (hopefully this month).

Are you planning on consuming the API with another app (which is totally fine - purely out of interest)?

**Comment by jspricke** [comment]
Yes, using it here: https://github.com/jspricke/radio/blob/master/tv#L38

**Comment by jspricke** [comment]
And thanks a lot for providing the API, btw!

**Comment by cemrich** [comment]
@jspricke Your changes are now live! Thanks again for your contribution :)

**Pull request merged**
